/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'gm2211' at '1/23/15 10:54 AM' with Gradle 2.1
 *
 * @author gm2211, @date 1/23/15 10:54 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
